Private registry image support and fixing windows to unix line feed char issue in shell command to retrieve triggers from a function app
ebencarek/azure-cli-extensions pull request #5
Opened 2020-06-27 00:48 UTC by SatishRanjan

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

2020-07-01 21:23 UTC, SatishRanjan commented
@ebencarek - can you please take a look at this PR.

2020-07-07 17:48 UTC, SatishRanjan commented
@ebencarek - request you to please take a look at it.

2020-07-07 17:51 UTC, ebencarek requested changes

2020-07-07 17:51 UTC, ebencarek commented on src/appservice-kube/azext_appservice_kube/custom.py
> +                            number_of_workers=None, location=None, tags=None, no_wait=False):
Remove trailing whitespace

2020-07-07 18:38 UTC, ebencarek approved these changes

2020-07-07 18:38 UTC, merged

2020-07-07 18:57 UTC, SatishRanjan commented
Thanks @ebencarek !